### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Fougere23** [hayden0729/berrybush#12]
``Python: Traceback (most recent call last):
  File "C:\Users\Louiji\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\blender\brresimport.py", line 1587, in execute
    BRRESImporter(context, brres.BRRES.unpack(fileData), self)
  File "C:\Users\Louiji\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\wii\brres.py", line 63, in unpack
    return BRRESReader().unpack(data).getInstance()
  File "C:\Users\Louiji\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\wii\brres.py", line 112, in unpack
    self.files[reader.DATA_TYPE] = folder.readEntries(data, reader)
  File "C:\Users\Louiji\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\wii\brresdict.py", line 67, in readEntries
    unpackedByOffset[offset] = entryType(self.parentSer, offset).unpack(data)
  File "C:\Users\Louiji\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\wii\mdl0.py", line 2260, in unpack
    raise ValueError("3D XSI transformations not currently supported")
ValueError: 3D XSI transformations not currently supported``

here's the file https://drive.google.com/file/d/1re6FYgLW4pFQj00itLd_pduouhLESjCa/view?usp=drive_link

There is a solution for this issue ?

**Comment by hayden0729** [comment]
Hi, thanks for the report. The problem lies in the "effect" model in this BRRES, which uses a set of conventions for bone scaling (Softimage/XSI) that isn't currently supported by BerryBush, as it's not used in New Super Mario Bros. Wii.

This isn't a perfect workaround, but you can change this value to "Maya" in BrawlCrate, which will change the conventions used. This might alter how some animations are evaluated, but then you should be able to import the model with BerryBush.
![image](https://github.com/user-attachments/assets/5e883487-1f93-480d-b308-0ed1af3a70de)

**Comment by Fougere23** [comment]
Now I can import the brres, thanks a lot !
