### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by CacaBueno64** [hayden0729/berrybush#8]
`Python: Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\blender\brresimport.py", line 1581, in execute
    BRRESImporter(context, brres.BRRES.unpack(fileData), self)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\blender\brresimport.py", line 1268, in __init__
    self._loadModel(model)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\blender\brresimport.py", line 1368, in _loadModel
    self.models[model] = BRRESMdlImporter(self, model)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\blender\brresimport.py", line 54, in __init__
    self._loadMat(mat)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\blender\brresimport.py", line 306, in _loadMat
    self._importTex(matSettings.textures.add(False), tex)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\berrybush\blender\brresimport.py", line 201, in _importTex
    texSettings.mapMode = f"{tex.mapMode.name}_{tex.coordIdx + 1}"
TypeError: bpy_struct: item.attr = val: enum "UV_-2" not found in ('UV_1', 'UV_2', 'UV_3', 'UV_4', 'UV_5', 'UV_6', 'UV_7', 'UV_8', 'PROJECTION', 'ENV_CAM', 'ENV_LIGHT', 'ENV_SPEC')
`
here's the file that I want to import :
https://mega.nz/file/g9cjjTRJ#BEuQ8jxz2pbNwC6HlRtN4q4G1wvU1Zt4ZxwXT1rriNk

**Comment by hayden0729** [comment]
Hi, thanks for the report! This a known bug caused by a BRRES material feature that's not used in NSMBW (using vertex colors as texture coordinates). This will be supported eventually, but in the meantime, you can get around it by making the "shading" texture of the soccer ball use regular UV mapping.

To do this with BrawlCrate, navigate here:
![image](https://github.com/hayden0729/berrybush/assets/69529462/91f5b3fe-f52a-4791-83b1-ab209ac5498c)
And change the **Type** and **Coordinates** fields as follows:
![image](https://github.com/hayden0729/berrybush/assets/69529462/c91d0533-58b3-43fe-9f1a-7c69ce47f711)
Then, it should be possible to import the model with BerryBush. This will change the appearance of the soccer ball, so if you want to maintain that after making changes, you can export and then change those fields back to their original values afterwards.

Until this is supported, if similar errors come up when importing other models, look for textures with similar settings ("Colors" mentioned in the type and coordinates). The workaround will be the same.

**Comment by CacaBueno64** [comment]
I managed to import it, thank you for taking the time to responding me

**Comment by CacaBueno64** [comment]
I'm now experiencing a new issue, there's no animations
the console writes :
`Unsupported BRRES folder 'AnmScn(NW4R)' detected & ignored`

**Comment by hayden0729** [comment]
Reopening until this is fixed

**Comment by NitroShellMKDS** [comment]
> Hi, thanks for the report! This a known bug caused by a BRRES material feature that's not used in NSMBW (using vertex colors as texture coordinates). This will be supported eventually, but in the meantime, you can get around it by making the "shading" texture of the soccer ball use regular UV mapping.
> 
> To do this with BrawlCrate, navigate here: ![image](https://github.com/hayden0729/berrybush/assets/69529462/91f5b3fe-f52a-4791-83b1-ab209ac5498c) And change the **Type** and **Coordinates** fields as follows: ![image](https://github.com/hayden0729/berrybush/assets/69529462/c91d0533-58b3-43fe-9f1a-7c69ce47f711) Then, it should be possible to import the model with BerryBush. This will change the appearance of the soccer ball, so if you want to maintain that after making changes, you can export and then change those fields back to their original values afterwards.
> 
> Until this is supported, if similar errors come up when importing other models, look for textures with similar settings ("Colors" mentioned in the type and coordinates). The workaround will be the same.

Hey buddy it's been 2 years, not to nag you but are you ever going to work on it?

**Comment by hayden0729** [comment]
Hi, yes this is still planned and will be supported in the next major release. I regrettably have much less free time than I used to so things have been moving slower, but I am still committed to this.
